spring.application.name=apiusuario

spring.datasource.url=jdbc:postgresql://localhost:5432/Incendios
spring.datasource.username=Incendios
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update